# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-powershell
name: Build klein

on: 
  # push:
  workflow_dispatch:

jobs:
  pester-test:
    name: Pester test    
    runs-on: windows-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build Powershell Module
        shell: pwsh
        run: |
          ./Helper/build.ps1
