# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-powershell
name: Test PowerShell

on: 
  # push:
  workflow_dispatch:

jobs:
  pester-test:
    name: Pester test
    runs-on: windows-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # - name: Perform a Pester test from the command-line
      #   shell: pwsh
      #   run: Test-Path resultsfile.log | Should -Be $true

      - name: Perform a Pester test from the Tests.ps1 file
        shell: pwsh
        run: |
          ./Tests/All.Tests.ps1


          # Invoke-Pester Unit.Tests.ps1 -Passthru