name: Test Powershell Module with Pester

on:
  - push
  - workflow_dispatch

jobs:
  pester-test:
    name: Pester test
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Perform a Pester test from the Tests.ps1 file
        shell: pwsh
        run: |
          ./Tests/All.Tests.ps1 -Passthru
